#!/bin/bash

# Build karabiner configuration from modular YAML files
# Combines main.yaml, base.yaml, and wez.yaml into karabiner.yaml and karabiner.json

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Building karabiner configuration..."

# Check that required files exist
for file in main.yaml base.yaml wez.yaml; do
    if [[ ! -f "$file" ]]; then
        echo "Error: Required file '$file' not found" >&2
        exit 1
    fi
done

# Generate dynamic wez.yaml from whitelist template
echo "Generating dynamic Wezterm rules..."
echo "# This file is auto-generated by build.sh - do not edit manually" > wez_generated.yaml
yq eval-all '
select(fileIndex == 0) as $config |
$config.wezterm_rule_template |
.manipulators += ($config.wezterm_ctrl_keys | map({
  "conditions": [
    {"bundle_identifiers": ["^com\\.github\\.wez\\.wezterm$"], "type": "frontmost_application_if"},
    {"name": "wez_cmd", "type": "variable_if", "value": 1}
  ],
  "from": {"key_code": ., "modifiers": {"optional": ["any"]}},
  "to": [{"key_code": ., "modifiers": ["left_control"]}],
  "type": "basic"
})) |
.manipulators += ($config.wezterm_cmd_keys | map({
  "conditions": [
    {"bundle_identifiers": ["^com\\.github\\.wez\\.wezterm$"], "type": "frontmost_application_if"},
    {"name": "wez_cmd", "type": "variable_if", "value": 1}
  ],
  "from": {"key_code": ., "modifiers": {"optional": ["any"]}},
  "to": [{"key_code": ., "modifiers": ["left_command"]}],
  "type": "basic"
}))

' wez.yaml >> wez_generated.yaml

# Combine the YAML files  
echo "Combining YAML files..."
echo "# This file is auto-generated by build.sh - do not edit manually" > karabiner.yaml
yq eval-all '. as $main | load("base.yaml") as $base | load("wez_generated.yaml") as $wez | $main | .profiles[0].complex_modifications.rules = [$base, $wez]' main.yaml >> karabiner.yaml

# Convert to JSON with sorted keys
echo "Converting to JSON..."
yq -o json karabiner.yaml | jq --sort-keys . > karabiner.json

echo "✓ Generated karabiner.yaml"
echo "✓ Generated karabiner.json"
echo "Configuration build complete!"